//AErdCollisionGroupTemplate.mel

global proc AErdCollisionGroupTemplate(string $nodeName) {
    editorTemplate -beginScrollLayout;

        editorTemplate -beginLayout "General" -collapse false;
            editorTemplate -addControl "enabled";
            editorTemplate -addControl "export";
            editorTemplate -addControl "color";
        editorTemplate -endLayout;

    editorTemplate -endScrollLayout;
    editorTemplate -suppress "Extra Attributes";
}
